[window]
dimensions = { columns = 2, lines = 1 }
padding = { x = 0, y = 0}
dynamic_padding = false
decorations = "None"
startup_mode = "Windowed"
dynamic_title = true

[scrolling]
history = 1000
multiplier = 8

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold"}
italic = { family = "JetBrains Mono", style = "Italic"}
size = 12
glyph_offset = { x = 0, y = -1}
offset = { x = 0, y = 0}

[colors]
selection = { text = "#363848", background = "#F8F8F2" }
cursor = { text = "#282A36", cursor = "#F8F8F2" }

[colors.primary]
foreground = "#F8F8F2"
background = "#282A36"

[colors.normal]
black = '#191A21'
red = '#FF5555'
green = '#50FA7B'
yellow = '#F1FA8C'
blue = '#8BE9FD'
magenta = '#BD93F9'
cyan = '#8BE9FD'

[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Never"}

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
 { key = "LBracket",  mods = "Control", mode = "~Search",  action = "ToggleViMode"   },
 { key = "Period",    mods = "Control",                    action = "ClearLogNotice" },
 { key = "Key1",      mods = "Control",                    chars = "\u001b1"         },
 { key = "Key2",      mods = "Control",                    chars = "\u001b2"         },
 { key = "Key3",      mods = "Control",                    chars = "\u001b3"         },
 { key = "Key4",      mods = "Control",                    chars = "\u001b4"         },
 { key = "Key5",      mods = "Control",                    chars = "\u001b5"         },
 { key = "Key6",      mods = "Control",                    chars = "\u001b6"         },
 { key = "Key7",      mods = "Control",                    chars = "\u001b7"         },
 { key = "Key8",      mods = "Control",                    chars = "\u001b8"         },
 { key = "Key9",      mods = "Control",                    chars = "\u001b9"         },
 { key = "Key0",      mods = "Control",                    chars = "\u001b0"         },
]
