theme = "dracula"

[keys.normal]
Z = {X = ":quit!", Z = ":write-quit!"}
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
L = "goto_line_end"
H = "goto_first_nonwhitespace"
esc = ["collapse_selection", "keep_primary_selection"]
D = ["ensure_selections_forward", "extend_to_line_end"]

[keys.normal.space]
o = "file_picker_in_current_buffer_directory"

[editor]
color-modes = true
cursorline = true
line-number = "relative"
rulers = [80, 100]

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "╎", "⸽"
skip-levels = 1

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.soft-wrap]
enable = true
