#!/bin/sh

alias dot="$DOTFILES"
alias dots="$DOTFILES"
alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias pacrl='rm /var/lib/pacman/db.lck'

### Exa
alias ls='exa'
alias la='exa -a'
alias ll='exa -laHF'

### Neovim
alias vim='nvim'
alias vi='nvim'
alias svim='sudoedit'
alias dvim='nvim --noplugin -u NONE'

### Ripgrep
alias rgp='rg -p'
alias rgr='rg -uuu'

### Rust
alias carb='cargo build'
alias carbr='cargo build --release'
alias carr='cargo run'
alias cari='cargo install'
alias carn='cargo new'
alias carnl='cargo new --lib'

### Yarn
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
