#!/bin/sh

alias dot="$DOTFILES"
alias dots="$DOTFILES"
alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias pacrl='rm /var/lib/pacman/db.lck'
alias n="note.sh"

### Exa
alias ls='exa'
alias la='exa -a'
alias ll='exa -laHF'
alias lt='exa -T'
alias lti-'exa -T --icons'

### Neovim
alias vim='nvim'
alias vi='nvim'
alias svim='sudoedit'
alias dvim='nvim --noplugin -u NONE'

### Ripgrep
alias rgp='rg -p'
alias rgr='rg -uuu'

### Rust
alias cb='cargo build'
alias cbr='cargo build --release'
alias cr='cargo run'
alias ci='cargo install'
alias cnb='cargo new'
alias cnl='cargo new --lib'
