#!/bin/sh

alias dot="$DOTFILES"
alias dots="$DOTFILES"
alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias pacrl='sudo rm /var/lib/pacman/db.lck'
alias nn="note"
alias nf="note_find"
alias t="ctags -R --exclude=@$DOTFILES/ctags/ctagsignore ."

### Exa
alias ls='exa'
alias la='exa -a'
alias ll='exa -laHF'
alias lt='exa -T'
alias lti-'exa -T --icons'

### Helix
alias hx='helix'
### Neovim
alias sudovi='sudo nvim'
alias vim='nvim'
alias vi='nvim'
alias svim='sudoedit'
alias dvim='nvim --noplugin -u NONE'

### Ripgrep
alias rgp='rg -p'
alias rgr='rg -uuu'

### Rust
alias cb='cargo build'
alias cbr='cargo build --release'
alias cr='cargo run'
alias ci='cargo install'
alias cnb='cargo new'
alias cnl='cargo new --lib'
alias ct='cargo test'

### Hardhat
alias nht='npx hardhat test'
alias nhn='npx hardhat node'
alias npr='npx hardhat run'
