#!/bin/sh

#ln -sf "$DOTFILES/scripts/bspwm_external_rules" "$HOME/bin/bspwm_external_rules"
#ln -sf "$DOTFILES/scripts/bspwm_move" "$HOME/bin/bspwm_move"
#ln -sf "$DOTFILES/scripts/bspwm_multinode" "$HOME/bin/bspwm_multinode"
#ln -sf "$DOTFILES/scripts/bspwm_presel" "$HOME/bin/bspwm_presel"
#ln -sf "$DOTFILES/scripts/bspwm_resize" "$HOME/bin/bspwm_resize"
#ln -sf "$DOTFILES/scripts/dunst.sh" "$HOME/bin/dunst.sh"
#ln -sf "$DOTFILES/scripts/ext_monitor" "$HOME/bin/ext_monitor"
#ln -sf "$DOTFILES/scripts/launch.sh" "$HOME/bin/launch.sh"
#ln -sf "$DOTFILES/scripts/theme.sh" "$HOME/bin/theme.sh"
ln -sf "$DOTFILES/scripts/sysup" "$HOME/bin/sysup"
ln -sf "$DOTFILES/scripts/note.sh" "$HOME/bin/note.sh"
ln -sf "$DOTFILES/scripts/todo" "$HOME/bin/todo"
ln -sf "$DOTFILES/scripts/note_find.sh" "$HOME/bin/note_find.sh"
ln -sf "$DOTFILES/scripts/sway_move" "$HOME/bin/sway_move"
ln -sf "$DOTFILES/scripts/wayext_monitor" "$HOME/bin/wayext_monitor"
#ln -sf "$DOTFILES/scripts/launch_switch_app" "$HOME/bin/launch_switch_app"
