#!/bin/sh

bemenu --hp 6 --fn "Jetbrains Mono 12 Bold" --nb "#1e1e2e" --nf "#cdd6f4" --hb "#f5e0dc" --hf "#1e1e2e" --fbb "#1e1e2e" --ab "#1e1e2e" --af "#cdd6f4" --tb "#1e1e2e" --tf "#cdd6f4" --fb "#1e1e2e" --ff "#cdd6f4" --cf "#f5e0dc"
