#!/bin/sh

node_file="$XDG_RUNTIME_DIR/bspwm_hidden_nodes.txt"

_query_nodes() {
	for i in $(bspc query -N -n "$1"); do
		"${@:2}" "$i"
	done
}

_get_node() {
	if [[ "$1" == --rn ]]; then
		target_node=$(tail --lines=1 "$node_file");
		sed -i '$d' "$node_file";
	elif [[ -n "$1" ]]; then
		target_node=$(rg "$1" "$node_file");
		rg -v "$1" "$node_file" > "${node_file}.tmp";
		mv "${node_file}.tmp" "$node_file";
	else
		target_node=$(head --lines=1 "$node_file");
		sed -i '1d' "$node_file";
	fi
	echo "$target_node"
}

_hide_node() {
	echo "$1" >> "$node_file";
	bspc node "$1" --flag hidden=on
}

_unhide_node() {
	target_node=$(_get_node "$@")
	bspc node "$target_node" --to-desktop focused;
	bspc node "$target_node" --flag hidden=off;
	bspc node -f "$target_node"
}

case "$1" in
	--nh|--hide-target-node)
		_query_nodes 'focused' _hide_node
				;;
	--nur|--unhide-most-recent-node)
		_unhide_node --rn
		;;
	--nuo|--unhide-oldest-node)
		_unhide_node
		;;
	--nha|--hide-all-nodes)
		_query_nodes '.local.window' _hide_node
		;;
	--nhnf|--hide-non-focused-nodes)
		_query_nodes '.!focused.!marked.local.window' _hide_node
		;;
	--nua|--unhide-all-nodes)
		while [[ -s "$node_file" ]]; do
			_unhide_node --rn
		done
		;;
	--nlu|--unhide-nodes-local)
		_query_nodes '.local.hidden' _unhide_node
		;;
	--nfu|--unhide-force-all)
		for i in $(bspc query -N -n '.hidden'); do bspc node "$i" -g hidden=off; done
		: > "$node_file"
esac
