#!/bin/sh

_query_nodes() {
	for i in $(bspc query -N -n "$1"); do
		bspc node "$i" "${@:2}"
	done
}

case "$1" in
	--rk|--kill-all-receptacles)
		_query_nodes '.leaf.!window' -k
		;;
	--nca|--close-all-local-non-focused)
		_query_nodes '.!focused.!marked.local.window' -c
		;;
	--nka|--kill-all-local-non-focused)
		_query_nodes '.!focused.!marked.local.window' -k
		;;
	--nla|--lock-all-local)
		_query_nodes '.local.window' -g locked=on
		;;
	--nula|--unlock-all-local)
		_query_nodes '.local.window' -g locked=off
		;;
	--nms|--summon-all-marked)
		_query_nodes '.marked' -d focused --follow
		;;
	--db|--bring-desktop-here)
		for i in $(bspc query -N -d "$2" -n '.window'); do
			bspc node "$i" -d 'focused.focused'
		done
		;;
	--ds|--send-desktop-there)
		_query_nodes 'any.local' -d "$2"
		;;
	--dsnf|--send-desktop-there-non-focused)
		_query_nodes '.!focused.!marked.local.window' -d "$2"
		;;
	--dsf|--send-desktop-follow)
		_query_nodes 'any.local' -d "$2" --follow
		;;
esac

