#!/bin/sh

ext_monitor=$(xrandr --query | rg 'DP1')
if [[ $ext_monitor = *connected* ]]; then
      xrandr --output eDP1 --primary --mode 3456x2160 --rotate normal --output DP1 --mode 1920x1080 --rotate right --right-of eDP1
fi
