#!/bin/sh

NOTES_DIR=$HOME/Notes
echo "$NOTES_DIR"
DATE=$(date +"%Y%m%d%H%M")

file_name() {
	if [[ -n $@ ]]; then
		echo "$DATE-$@.md"
	else
		echo "$DATE.md"
	fi
}

FILE="$NOTES_DIR/$(file_name $@)"
TITLE=$(echo $@ | tr '-' ' ' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1')

echo "# $TITLE" > $FILE
echo $(date) >> $FILE
nvim $FILE

CWD=$(pwd)
cd "$NOTES_DIR"
git add -A
git commit -m "$FILE"
ctags -R .
cd $CWD
