#!/bin/sh

NOTES_DIR="$HOME/Notes/"
echo "$NOTES_DIR/journal"
DATE=$(date +"%Y%m%d")

file_name() {
	if [[ -n $@ ]]; then
		echo "$DATE-$@.md"
	else
		echo "$DATE.md"
	fi
}

FILE="$NOTES_DIR/journal/$(file_name $@)"

echo $(date) > $FILE
nvim $FILE

CWD=$(pwd)
cd "$NOTES_DIR/journal"
git add -A
git commit -m "$FILE"
ctags -R .
cd $CWD
