#!/bin/sh

echo "$HOME/docs/notes/journal"
DATE=$(date +"%Y%m%d")

file_name() {
	if [[ -n $@ ]]; then
		echo "$DATE-$@.md"
	else
		echo "$DATE.md"
	fi
}

FILE="$HOME/docs/notes/journal/$(file_name $@)"

echo $(date) > $FILE
helix $FILE

CWD=$(pwd)
cd "$HOME/docs/notes/journal"
git add -A
git commit -m "$FILE"
ctags -R .
cd $CWD
