#!/bin/sh

echo $NOTES_DIR
DATE=$(date +"%Y%m%d%H%M")

file_name() {
	if [[ -n $@ ]]; then
		echo "$DATE-$@.md"
	else
		echo "$DATE.md"
	fi
}

FILE="$NOTES_DIR/$(file_name $@)"

echo $(date) > $FILE
helix $FILE

CWD=$(pwd)
cd $NOTES_DIR
git add -A
git commit -m "$FILE"
ctags -R .
cd $CWD
