#!/bin/sh

echo "$HOME/docs/notes"
DATE=$(date +"%Y%m%d%H%M")

file_name() {
	if [[ -n $@ ]]; then
		echo "$DATE-$@.md"
	else
		echo "$DATE.md"
	fi
}

FILE="$HOME/docs/notes/$(file_name $@)"

echo $(date) > $FILE
nvim $FILE

CWD=$(pwd)
cd "$HOME/docs/notes"
git add -A
git commit -m "$FILE"
ctags -R .
cd $CWD
