#!/bin/fish
 
if test -d "venv"
	set VENV_PATH "venv"
else if test -d ".venv" 
	set VENV_PATH ".venv"
else
	echo "No virtual environment found"
	exit 1
end

set PYTHON_LIB_DIR (fd -t d '^python' "$VENV_PATH/lib/" --max-depth 1)

if test -z "$PYTHON_LIB_DIR"
	echo "No python library directory found in $VENV_PATH/lib"
	exit 1
end

set PYTHON_LIB_DIR (echo "$PYTHON_LIB_DIR" | sed 's:/*$::')
set PYTHON_LIB_DIR "$PYTHON_LIB_DIR/site-packages"

set -xg PYTHONPATH "$PWD/$PYTHON_LIB_DIR"
echo $PYTHONPATH
