#!/bin/sh

DATE=$(date +"%Y%m%d")
DIRPATH="$HOME/docs"
FILE="$DIRPATH/todo/$DATE.md"

if [[ ! -e $FILE ]]; then
	touch "$FILE.md"
fi

nvim $FILE
git -C $DIRPATH add -A
git -C $DIRPATH commit -m "TODOs for '$DATE'"
