#!/bin/sh

DATE=$(date +"%Y%m%d")
FILE="$NOTES_DIR/$DATE.md"

if [[ ! -e $FILE ]]; then
	touch "$FILE.md"
	echo "# Todos for $(date +"%a %d %b %Y")  " > $FILE
	echo "@todo" >> $FILE
fi

nvim $FILE
git -C $NOTES_DIR add -A
git -C $NOTES_DIR commit -m "TODOs for '$DATE'"
