#!/bin/zsh

export PATH=$PATH:$HOME/bin:$HOME/.local/bin
export TERM='alacritty'
export DOTFILES="$HOME/.dotfiles"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# other
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# fzf
export FZF_DEFAULT_COMMAND="rg --files --no-ignore-vcs --hidden"
export FZF_COMPLETION_OPTS="+c -x"
export FZF_DEFAULT_OPTS="--height 60% --layout reverse --inline-info --color --multi --extended"
fzf_compgen_path() {
  fd --no-ignore-vcs --follow --exclude ".git" . "$1"
}

_fzf_compogen_dir() {
  fd --type d --no-ignore-vcs --follow --exclude ".git" . "$1"
}

# X11
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug

# Python
export PYTHONPATH=/usr/local/bin/python3

# NPM
export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/node_modules/npmrc"
