#!/bin/zsh

export PATH=$PATH:$HOME/bin:$HOME/.local/bin
#export TERM='alacritty'
export DOTFILES="$HOME/.dotfiles"
export CLICOLOR=1
export NOTES_DIR="$HOME/docs/notes"
export PATH=$PATH:$HOME/Scripts

# homebrew
export PATH=/opt/homebrew/bin:$PATH

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# other
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export IPFS_PATH="$XDG_DATA_HOME/ipfs"

# fzf
export FZF_DEFAULT_COMMAND="rg --files --no-ignore-vcs --hidden"
export FZF_COMPLETION_OPTS="+c -x"
export FZF_DEFAULT_OPTS="--height 60% --layout reverse --inline-info --color --multi --extended"
fzf_compgen_path() {
  fd --no-ignore-vcs --follow --exclude ".git" . "$1"
}

_fzf_compogen_dir() {
  fd --type d --no-ignore-vcs --follow --exclude ".git" . "$1"
}

# X11
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export PATH="$CARGO_HOME/bin:$PATH"
export RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug

# Python
export PYTHONPATH=/usr/local/bin/python3

# Ruby
export PATH="$XDG_DATA_HOME/gem/ruby/3.0.0/bin:$PATH"

# NPM
export NPM_PATH="$XDG_DATA_HOME/npm"
export NPM_BIN="$XDG_DATA_HOME/npm/bin"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PATH="$NPM_BIN:$PATH"

# LESS
export LESSKEY="$XDG_CONFIG_HOME/less/lesskey"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

# nnn
if [ -f /usr/share/nnn/quitcd/quitcd.bash_zsh ]; then
    source /usr/share/nnn/quitcd/quitcd.bash_zsh
fi

#GCP
export PATH="$XDG_DATA_HOME/google-cloud-sdk/bin:$PATH"

# Solana
export PATH="$XDG_DATA_HOME/solana/install/active_release/bin:$PATH"
