#!/bin/zsh


### Navigation
setopt AUTO_CD              # Go to folder path without using cd.

setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

### Autojump
[[ -s /etc/profile.d/autojump.sh ]] && source /etc/profile.d/autojump.sh # Jump to a folder previously visited with j <FILE>

setopt CORRECT              # Spelling correction
setopt CDABLE_VARS          # Change directory to a path stored in a variable.
setopt EXTENDED_GLOB        # Use extended globbing syntax.

### History
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

### Zsh Completion
autoload -U compinit; compinit

#(cat ~/.cache/wal/sequences &)
#source ~/.cache/wal/colors-tty.sh

### Aliases
source $DOTFILES/aliases/aliases

### Vi Mode
set -o vi
export KEYTIMEOUT=1
bindkey -v

### Plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

### Prompt
function zle-line-init zle-keymap-select {
  PROMPT=`$DOTFILES/zprs/target/release/zprs precmd;$DOTFILES/zprs/target/release/zprs prompt -k "$KEYMAP" -r "$?"`
  zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

### Keybinds
zle -N fzf-cd-widget
bindkey '^R' fzf-cd-widget
bindkey -rpM viins '^['
bindkey -rpM vicmd '^['
bindkey -rpM viopp '^['
bindkey -rpM visual '^['
bindkey '^G' kill-line 
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
