[theme]
name = "gruvbox-dark"
[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "net"
on_click = "alacritty -e nmtui"
device = "wlp0s20f3"
format = "{ssid} {signal_strength} {ip}{speed_down;K*b:1}"
interval = 5

[[block]]
block = "sound"
step_width = 5
format = "{output_description} {volume}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization:1}" 

[[block]]
block = "memory"
format_mem = "{mem_used_percents:1}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average:1}C"

[[block]]
block = "battery"
format = "{percentage}"

[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "Europe/London"
interval = 5 
locale = "en_GB"
